version: "3"
volumes:
  php-fpm-socket:
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports: ["8888:80"]
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=100M
    depends_on: ["mysql"]

  php:
    build: ./php
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./apps:/var/www/html:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      # - ./php/php-fpm.d/zzz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
      # - php-fpm-socket:/var/run/php-fpm
    depends_on: ["mysql"]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/local.conf
      - ./apps:/var/www/html
      - ./nginx/log/access.log:/var/log/nginx/access.log
      - ./nginx/log/error.log:/var/log/nginx/error.log
    ports: ["80:80"]
    depends_on: ["php"]

  # queue:
    # build: ./php
    # volumes:
      # - ./apps/cheerup:/var/www/html:delegated
      # - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    # entrypoint: ["php", "artisan", "horizon"]
    # working_dir: /var/www/html

  redis:
    image: redis:latest
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
